### ISSUE TITLE
Add support for marking emails as read or unread

### ISSUE THREAD

**Issue by Kabouik** [dantecatalfamo/himalaya-emacs#22]
Thanks for this very nice package!

Marking emails as read or unread is very central in the workflow of many users, I myself often use that to ~~postpone email replies~~ procrastinate, and easily find emails I didn't treat later. The feature is already` supported in the CLI with `himalaya flag remove id -- seen`, and reciprocally, so hopefully that should be relatively easy to implement. I can try looking into it but I know nothing in Elisp so it won't be trivial for me and I risk either failing or creating new bugs.

**Comment by soywod** [comment]
Feature added in https://github.com/dantecatalfamo/himalaya-emacs/pull/23. `C-c +` to add a flag, `C-c -` to remove one.

**Comment by soywod** [comment]
With the `v1.0.0-beta`, a new flag has been introduce to the command `message read` called `--preview` which prevent the `seen` flag to be applied to the associated envelope. Is it sth @Kabouik you could be interested in to have inside the Emacs plugin? The `RET` mapping already exists to read a message, we could imagine a `C-u RET` to preview a message.

**Comment by Kabouik** [comment]
Nice! Absolutely, I think that'd be interesting to have that in the Emacs package. To be honest, I haven't taken the time to experiment more with Himalaya as I am very happy with d99kris/nmail, but Himalaya and aerc are alternatives I would really like to try as they would allow different workflows, and the existence of an Emacs package is appealing.
