### ISSUE TITLE
Email query

### ISSUE THREAD

**Issue by dantecatalfamo** [dantecatalfamo/himalaya-emacs#4]
Add an interface for `himalaya query`

**Comment by soywod** [comment]
Just a remark here. For now, the `query` command from the CLI takes a simple string. The API depends on the backend used. For example, if you use the IMAP backend, then the query needs to be a valid IMAP query as described in the RFC, sth like "not seen and from sende@local". But if you use the Notmuch backend, the query needs to be a valid Notmuch query like "tag:seen and from:sender@local".

It is clearly not optimal. The best is to have a common API, a Himalaya query system that internally maps to the correct backend-specific query system. So be aware that the query command may change in the future (and may potentially breaks frontends).

**Comment by soywod** [comment]
This feature will be doable after https://todo.sr.ht/~soywod/pimalaya/39, which should come very soon in the pipeline.

**Comment by soywod** [comment]
Feature on its way :tada:
